"""empty message

Revision ID: 01213c21f0c0
Revises: 5c5da3c9e725
Create Date: 2019-09-28 14:54:35.630358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01213c21f0c0'
down_revision = '5c5da3c9e725'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'list_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'list_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
